[package]
name = "excel_to_json"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
calamine = "0.25.0"
chrono = "0.4.38"
serde = "1.0.208"
serde_json = "1.0.125"
wasm-bindgen = "0.2"
