name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build wasm
        run: wasm-pack build --target nodejs

      - name: Move files to publish directory
        run: rsync -av --exclude='package.json' --exclude='README.md' --exclude='.gitignore' pkg/ publish/ 

      - name: Configure npm to use the registry
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd publish
          npm publish --access=public